version: '3'

services: 

  limesurvey:
    container_name: limesurvey
    build:
        context: ./limesurvey
        dockerfile: Dockerfile
    depends_on:
        - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PORT: '3306'
      MYSQL_PASSWORD: mynewpassword
      MYSQL_DB: limesurvey
    ports:
        - 8080:80
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: system-fluentd-1:24224
        tag: limesurvey.access

  monit:
    build:
      context: ./monit
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "2812:2812"
  
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: mynewpassword
        MYSQL_DATABASE: limesurvey
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
        - "9906:3306"

  adminer:
    image: adminer
    ports:
      - '8888:8080'


  fluentd: 
    build: ./fluentd
    links: # Sends incoming logs to the elasticsearch container.
      - elasticsearch
    depends_on:
      - elasticsearch
    ports: # Exposes the port 24224 on both TCP and UDP protocol for log aggregation
      - 24224:24224
      - 24224:24224/udp


  elasticsearch:
    image: elasticsearch:8.7.1
    expose: # Exposes the default port 9200
      - 9200
    environment:
      - discovery.type=single-node # Runs as a single-node
    volumes: # Stores elasticsearch data locally on the esdata Docker volume
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.7.1
    links: # Links kibana service to the elasticsearch container
      - elasticsearch
    depends_on:
      - elasticsearch
    ports: # Runs kibana service on default port 5601
      - 5601:5601
    environment: # Defined host configuration
      - ELASTICSEARCH_HOSTS=http://consttier.tech:9200

  

volumes:
  mysql_data: 
  esdata:
